language: java
jobs: 
  include: 
    - stage: build
      script: "sh './scripts/build.sh'"
    - stage: test
      script: "sh './scripts/test.sh'"
    - stage: deploy	
      script: "echo 'i do a ! deploy'"
      
