
language: java

before_install:
  - cd src/wms
#jdk:
#  - oraclejdk8
  #- oraclejdk11

jdk:
 - openjdk8
 - openjdk11




#jobs: 
#  include: 
#    - stage: build
#      name: building-project
#      script: "sh './scripts/build.sh'"
#    - stage: test
#      name: test on jdk8
#      jdk: openjdk8
#      script:
#      - "sh './scripts/tests.sh'"
#    - name: test on jdk11
#      jdk: oraclejdk11
#      script: 
#      - "sh './scripts/tests.sh'"
#    - stage: deploy	
#      script: "sh './scripts/deploy.sh'"
#deploy:
#      name: deploying
#      provider: releases
#      api_key: $GITHUB_API_KEY
#      skip_cleanup: true
#      on:
#        tags: true
#        all_branches: true
#      #script: "sh './scripts/deploy.sh'"

