--- 
cache:
  directories:
    - "$HOME/.m2"
    - downloads

language: java
jobs: 
  include: 
    - stage: build
      # phase de build
      # script: "sh \"./scripts/build.sh\""
      # generation de la doc web statique
      script: sh './scripts/build.sh'
      
    - stage: test
      script: echo 'do tests'
      #script: "sh \"./scripts/tests.sh\""
      
    - stage: deploy
      script: "echo \"i do a deploy!\""
      


matrix:
  include:
    - jdk: oraclejdk8
      dist: trusty
      env: ACTION=build ARGS="-Dfmt.skip=true" COMMUNITY_ARGS=$ARGS 
      name: Java 8 build
    - jdk: openjdk11
      env: ACTION=build ARGS="-Dfmt.skip=true" COMMUNITY_ARGS=$ARGS
      name: Java 11 build
    - jdk: openjdk11
      env: ACTION=build ARGS="-Dfmt.action=check -Dqa -DskipTests=true" COMMUNITY_ARGS="-Dfmt.action=check -DskipTests=true"
      name: QA build on Java 11
    - jdk: openjdk11
      env: ACTION=docs
      name: Documentation build
    - jdk: openjdk11
      env: ACTION=package
      name: Build release packages
#test para:
#env:
#- TEST_SUITE="travis-job-codecov-linter.sh"
#- TEST_SUITE="travis-job-cypress-boxes.sh"
#- TEST_SUITE="travis-job-cypress-products.sh"
#- TEST_SUITE="travis-job-cypress-signup.sh"
#- TEST_SUITE="travis-job-cypress-controls.sh"
#- TEST_SUITE="travis-job-build.sh"
#script: ./${TEST_SUITE}
