--- 

#env:
#  - TESTFOLDER=src/wfs
#  - TESTFOLDER=src/wms

language: java

jobs: 
  include: 
    - stage: build
      # phase de build
      script: sh './scripts/build.sh'
      
    - stage: test
      script: sh './scripts/test.sh'
#      script: echo 'do tests'
#      name: WMS
#      script: mvn test -f src/wms
#      - name: WFS
#      script: mvn test -f src/wfs
	
      
    - stage: deploy
      script: echo 'i do a deploy!'

# script: skip
# deploy: &heroku
#  provider: heroku
#  app: sf-stages-staging
#  api_key: $HEROKU_AUTH_TOKEN


#test para:
#env:
#- TEST_SUITE="travis-job-codecov-linter.sh"
#- TEST_SUITE="travis-job-cypress-boxes.sh"
#- TEST_SUITE="travis-job-cypress-products.sh"
#- TEST_SUITE="travis-job-cypress-signup.sh"
#- TEST_SUITE="travis-job-cypress-controls.sh"
#- TEST_SUITE="travis-job-build.sh"
#script: ./${TEST_SUITE}
