--- 
jobs: 
  include: 
    - 
      script: "sh \"./scripts/build.sh\""
      stage: build
    - 
      script: "sh \"./scripts/tests.sh\""
      stage: test
    - 
      script: "echo \"i do a deploy!\""
      stage: deploy
language: java

