language: java

cache:
  directories:
  - $HOME/.m2

before_install:
  - cd src

jdk:
 - openjdk8
 - openjdk11

deploy:
    - name: deploying
      provider: releases
      api_key: $GITHUB_API_KEY
      skip_cleanup: true
      on:
        tags: true
        all_branches: true
        
install: true
script: 
    - mvn clean install





#jobs: 
#  include: 
#    - stage: build
#      name: building-project
#      script: "sh './scripts/build.sh'"
#    - stage: test
#      name: test on jdk8
#      jdk: openjdk8
#      script:
#      - "sh './scripts/tests.sh'"
#    - name: test on jdk11
#      jdk: oraclejdk11
#      script: 
#      - "sh './scripts/tests.sh'"
#    - stage: deploy	
#      script: "sh './scripts/deploy.sh'"
#deploy:
#      name: deploying
#      provider: releases
#      api_key: $GITHUB_API_KEY
#      skip_cleanup: true
#      on:
#        tags: true
#        all_branches: true
#      #script: "sh './scripts/deploy.sh'"

