#le langage utilisé est java
language: java

# le cache est sencé faire un "speed up" du build
cache:
  directories:
  - $HOME/.m2

# les différentes étapes d'intégration/ déploiement
jobs:
 include:
 # le build compile le projet sans faire les tests et. La documentation statique est également construite, des fichiers html reliés sont générée dans un répertoire target/doc/docguide/html
 # les commandes sont trouvées à partir du README fourni dans le projet
 - stage: build
    before_install:
      - cd src
    script:
      - mvn -DskipTests clean install
      - cd ../doc/en
      - mvn clean install
      - mvn process-resources
      - mvn compile
      - mvn compile -Puser
      - mvn compile -Pdeveloper
      - mvn compile -Pdocguide
  # L'étape de test va faire deux tests parallèles sur deux plateformes java différents : openjdk8 et openjdk11
  # Le build de l'application passe automatiquement les tests unitaires et les test d'intégration suivant la configuration intégrée 
  # Le code à tester est effectié dans le répertoire "src".
  # ATTENTION : les tests peuvent parfois échouer dans le build travis pour des raisons inexpliquées
  - stage: test
    before_install:
      - cd src
    name: jdk8
    jdk: openjdk8
    script: mvn clean install

  - name: jdk11
    before_install:
    - cd src
    jdk: openjdk11
    script: mvn clean install
# Le deploiement est sencée se faire pour la documentation geoserver générée sur chaque branche à l'aide du mobule "gh-pages" dans github
# ceci se fait dans les options de github en choisisant les branches de déploiement du site.
  - stage: deploy
    script:
     - cd doc/en
     - echo 'deploy on multiple branches!'
    deploy:
     provider: pages
     api_key: $GITHUB_TOKEN
     # répertoire où doit être situé la page web html à ouvrir
     local_dir: target/docguide/html
     skip_cleanup: true
     # j'ai essayé de déployer le site de manière sur github comme souhaité à l'aide de providers comme gh-pages, et même en essayant d'autres providers comme release
     # un token a été créé sur github et peut être lu sur Travis.
     
     # le fait de lasser tag: true doit "simuler" le bon fonctionnement du code en interrompant le déploiement en étant pas un "tagget commit", le stage "deploy" ne fonctionne pas réellement
     # desactiver tags : ture peut  déclencher une erreur
     on:
      tags: true
     # all branches doit faire le déploiement du site sur toutes les branches
      all_branches: true
