
language: java

jobs: 
  include: 
#    - stage: build
#      name: building-project
#      script: "sh './scripts/build.sh'"
    - stage: test
    - name: test on jdk8
      script: jdk_switcher use openjdk8
      script: "sh './scripts/tests.sh'"
    - name: test on jdk11
      script: jdk_switcher use openjdk11
      script: "sh './scripts/tests.sh'"
# do stuff with open Java 8
    - stage: deploy	
      name: deploying
      script: "sh './scripts/deploy.sh'"

