
language: java

jobs: 
  include: 
    - stage: build
      script: "sh './scripts/build.sh'"
    - stage: test
      script: "sh './scripts/tests.sh'"
    - stage: deploy	
      script: "sh './scripts/deploy.sh'"

