
language: java

jobs: 
  include: 
    - stage: build
      script: "sh './scripts/build.sh'"
    - stage: test
      script: "sh './scripts/tests.sh'"
	script:
	  - jdk_switcher use oraclejdk8
	  - # do stuff with Java 8
	  - jdk_switcher use openjdk8
	  - # do stuff with open Java 8
    - stage: deploy	
      script: "sh './scripts/deploy.sh'"

