
language: java
dist: trusty
os: linux
before_install:
  - rm ~/.m2/settings.xml
install:
  - sudo pip install sphinx requests
jobs: 
  include: 
#    - stage: build
#      name: building-project
#      script: "sh './scripts/build.sh'"
    - stage: test
      name: test on jdk8
#      jdk: oraclejdk8
      script:
      - jdk_switcher use openjdk8
      - "sh './scripts/tests.sh'"
    - name: test on jdk11
#      jdk: oraclejdk11
      script: 
      - jdk_switcher use openjdk11
      - "sh './scripts/tests.sh'"
    - stage: deploy	
      name: deploying
      script: "sh './scripts/deploy.sh'"

