
language: java
before_install:
  - rm ~/.m2/settings.xml
  - unset _JAVA_OPTIONS
install:
  - if [ "$ACTION" == "docs" ]; then sudo pip install sphinx requests; fi
jobs: 
  include: 
#    - stage: build
#      name: building-project
#      script: "sh './scripts/build.sh'"
    - stage: test
      name: test on jdk8
      script: 
      - jdk_switcher use openjdk8
      - "sh './scripts/tests.sh'"
    - name: test on jdk11
      script: 
      - jdk_switcher use openjdk11
      - "sh './scripts/tests.sh'"
    - stage: deploy	
      name: deploying
      script: "sh './scripts/deploy.sh'"

