--- 
jobs: 
  include: 
    - stage: build
      # phase de build
      # script: "sh \"./scripts/build.sh\""
      # generation de la doc web statique
      script: echo "hello"
      script: echo "World"
      
    - stage: test
      script: "sh \"./scripts/tests.sh\""
      
    - stage: deploy
      script: "echo \"i do a deploy!\""
      
language: java

